server:
  port: 8080

---
spring:
  application:
    name: demo-google-auth
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${TU_CLIENT_ID_DE_GOOGLE}
            client-secret: ${TU_CLIENT_SECRET_DE_GOOGLE}
            scope:
              - email
              - profile
          github:
            client-id: TU_CLIENT_ID_DE_GITHUB
            client-secret: TU_CLIENT_SECRET_DE_GITHUB
            scope:
              - read:user
              - user:email
